"""adicionando campos detalhados de paciente e gravidade

Revision ID: 513a54c1d760
Revises: 5d9f317757c6
Create Date: 2026-02-17 00:55:36.498734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '513a54c1d760'
down_revision = '5d9f317757c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('turno', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('prontuario', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('data_nascimento_paciente', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('quer_se_identificar', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('foto_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('houve_acao_imediata', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('gravidade', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('atualizado_por', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('data_atualizacao', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'usuarios', ['atualizado_por'], ['id'])
        batch_op.drop_column('severidade')
        batch_op.drop_column('houve_action_imediata')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('houve_action_imediata', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('severidade', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('data_atualizacao')
        batch_op.drop_column('atualizado_por')
        batch_op.drop_column('gravidade')
        batch_op.drop_column('houve_acao_imediata')
        batch_op.drop_column('foto_path')
        batch_op.drop_column('quer_se_identificar')
        batch_op.drop_column('data_nascimento_paciente')
        batch_op.drop_column('prontuario')
        batch_op.drop_column('turno')

    # ### end Alembic commands ###
