"""add evidencia_path to notificacoes

Revision ID: a1356824591a
Revises: cea75d691036
Create Date: 2026-02-17 14:47:47.756095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1356824591a'
down_revision = 'cea75d691036'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('evidencia_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificacoes', schema=None) as batch_op:
        batch_op.drop_column('evidencia_path')

    # ### end Alembic commands ###
