"""sincronizando colunas

Revision ID: cea75d691036
Revises: 3545e59e3db1
Create Date: 2026-02-17 09:23:36.108915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cea75d691036'
down_revision = '3545e59e3db1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itens_formulario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('titulo', sa.String(length=100), nullable=False))
        batch_op.alter_column('categoria',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('nome')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itens_formulario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
        batch_op.alter_column('categoria',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('titulo')

    # ### end Alembic commands ###
